### ISSUE TITLE
Pod stuck in migration

### ISSUE THREAD

**Issue by talonx** [zalando-incubator/es-operator#260]
## Expected Behavior
Shards remain stuck in migration.

## Actual Behavior
Shards should migrate.

## Steps to Reproduce the Problem

  1. Change resource request of an existing statefulset (ES data nodes) which has 3 pods
  2. The operator creates a new pod and starts draining one of the old pods
  3. All shards should move to the new pod and the old pod can then be deleted

Instead, we see this message continuously in the operator logs
```
level=info msg="Found 170 remaining shards on ..... "' <snipped>
```
This message has been coming continuously for 24 hours and the shard movement is stuck. 

Any ideas on what can wrong or how to fix this?

## Specifications

  - Version:
  - Platform: GKE
  - Subsystem:

**Comment by otrosien** [comment]
Hey @talonx, there could be many reasons for this status. the most common ones are:

* Elasticsearch configuration prohibiting more co-location of shards. This could be because of reaching disk threshold, reaching the maximum number of shards of the same index on the same node (index setting), this could be related to shard allocation with zone-awareness, prohibiting more skew among the data distribution
* It could be caused by timeouts while ES is trying to relocate a shard. (check output of `/_cat/shards` for relocations starting and cancelling after some time)
* It could be that you're in the middle of a version upgrade and you need to provide more nodes of the new version in order to allow ES to relocate shards without violating aforementioned constraints

Please check what ES logs state, and the different diagnostics endpoints of ES.

**Comment by talonx** [comment]
@otrosien thanks for the response. The shard migration went through - it just took a long time so I thought nothing was progressing. The operator logs were stuck at the same message which was another reason for this assumption.
