### ISSUE TITLE
Avoid node draining during rolling upgrade when using PVC

### ISSUE THREAD

**Issue by mikkeloscar** [zalando-incubator/es-operator#70]
Several people have asked if the operator can somehow avoid node draining in cases where you have a PVC and don't actually need the draining in order to safely move the data around.

If possible we should add a feature where we can prepare a node for update by making sure it doesn't get traffic (not sure how to do this) and then simply delete the pod and let Kubernetes schedule it and attach the PVC on the new pod. Once ready, it can again get traffic.

Draining would still be needed in case of scaledown to ensure there is no data loss (depending on index configuration).

**Comment by otrosien** [comment]
There's no way to tell Elasticsearch to make a node not getting traffic unless you drain the data. I think the SIGTERM would allow ES to still complete in-flight requests, but not sure. If not, clients would just need to retry the failed trquests.

Proposed implementation: Extend the EDS spec to skip draining. The rest would still apply. So the scale-down only happens if cluster health is green. It will temporarily turn yellow, and we would need to wait for the cluster to turn green again before performing the next operation.
